import type { Snapshot } from "./types";

/**
 * Bundled demo data, used only when NOTION_TOKEN is unset (local dev, tests).
 * The FaithLink field log here deliberately carries the version drift observed
 * in the live August 2026 submission BEFORE it was caught — amount, program
 * name, persons served, ZIPs, board count, and a dropped MHFA component — so
 * the consistency checker can be exercised end-to-end without real data.
 */
export function fixtureSnapshot(): Snapshot {
  return {
    demo: true,
    fetchedAt: new Date().toISOString(),
    grants: [
      {
        id: "fixturefaithlink",
        notionUrl: "https://notion.so",
        org: "namifc",
        granteeOrg: "NAMI Franklin County",
        funder: "Franklin County Board of Commissioners — Community Partnerships",
        scope: "Health Equity Phase Two — FaithLink with Mental Health First Aid (MHFA) Expansion.",
        stage: "Final Round – Submitted",
        amount: 250000,
        submissionDeadline: "2026-08-07",
        submissionDate: "2026-08-07",
        inquiryDate: "2026-04-30",
        followUpBy: "2026-09-15",
        funded: null,
        finalRound: true,
        granteeContact: "Rachelle Martin",
        granteeEmail: "rachelle@namifc.org",
        tags: ["Nonprofit"],
        timeline:
          "Phase One LOI submitted 4/30/2026 at $250,000. Advanced to Phase Two 7/24/2026. Phase Two submitted 8/7/2026. Follow up with Community Partnerships if no decision by 9/15/2026.",
        applyingEntity: "External Client Only",
      },
      {
        id: "fixturenamioneohio",
        notionUrl: "https://notion.so",
        org: "namifc",
        granteeOrg: "NAMI Franklin County",
        funder: "OneOhio",
        scope: "Faith-Based Intergenerational Recovery and Prevention Program",
        stage: "Inquiry Submitted – Awaiting Decision",
        amount: 150000,
        submissionDeadline: null,
        submissionDate: null,
        inquiryDate: null,
        followUpBy: "2026-05-01",
        funded: null,
        finalRound: false,
        granteeContact: "Rachelle Martin",
        granteeEmail: "rachelle@namifc.org",
        tags: ["Nonprofit"],
        timeline: "Submitted OneOhio Cycle 2 at $150K. Check back May 1.",
        applyingEntity: "External Client Only",
      },
      {
        id: "fixturearkoneohio",
        notionUrl: "https://notion.so",
        org: "arkbuilders",
        granteeOrg: "ArkBuilders",
        funder: "OneOhio",
        scope: "Vaping, mobile gambling, adolescent SUD recovery supports",
        stage: "Inquiry Submitted – Awaiting Decision",
        amount: 150000,
        submissionDeadline: null,
        submissionDate: null,
        inquiryDate: "2026-02-02",
        followUpBy: "2026-05-01",
        funded: null,
        finalRound: false,
        granteeContact: "George Hicks",
        granteeEmail: "george@arkbuilders.org",
        tags: ["Nonprofit"],
        timeline: "Submitted OneOhio Cycle 2 at $150K. Awaiting decision.",
        applyingEntity: "Measurement Ally",
      },
      {
        id: "fixturearkpnc",
        notionUrl: "https://notion.so",
        org: "arkbuilders",
        granteeOrg: "ArkBuilders Inc.",
        funder: "PNC Charitable Trust",
        scope: "Youth vaping prevention (CATCH My Breath), sports gambling awareness, workforce pipeline",
        stage: "Final Round – Submitted",
        amount: 45000,
        submissionDeadline: null,
        submissionDate: null,
        inquiryDate: "2026-04-01",
        followUpBy: "2026-05-01",
        funded: null,
        finalRound: false,
        granteeContact: "George A. Hicks",
        granteeEmail: "george@arkbuilders.org",
        tags: ["Nonprofit"],
        timeline: "Full application submitted April 2026. Awaiting decision.",
        applyingEntity: "External Client Only",
      },
    ],
    orgFacts: [
      {
        id: "fixturenamifacts",
        org: "namifc",
        orgName: "NAMI Franklin County",
        legalName: "National Alliance on Mental Illness of Franklin County (NAMI FC)",
        ein: "31-1197905",
        yearFounded: 1987,
        address: "",
        website: "",
        primaryPhone: "",
        edName: "Rachelle Martin",
        edEmail: "rachelle@namifc.org",
        edPhone: "",
        fiscalContact: "",
        fyEnd: "2025-06-30",
        fyRevenue: 1443511,
        fyExpenditures: 1426167,
        operatingBudget: null,
        boardCount: 10,
        boardRace: "Black: 3, White: 7",
        boardGender: "Female: 9, Male: 1",
        staffRace: "",
        staffGender: "",
        topZips: "43203, 43219, 43211",
        guidestarUrl: "",
        lastVerified: "2026-08-07",
        verifiedBy: "Erica Tartt — verified during Phase Two submission",
      },
      {
        id: "fixturearkfacts",
        org: "arkbuilders",
        orgName: "ArkBuilders Inc.",
        legalName: "ArkBuilders Inc.",
        ein: "",
        yearFounded: null,
        address: "",
        website: "",
        primaryPhone: "",
        edName: "George A. Hicks, OCPC/LCPS",
        edEmail: "george@arkbuilders.org",
        edPhone: "",
        fiscalContact: "",
        fyEnd: null,
        fyRevenue: null,
        fyExpenditures: null,
        operatingBudget: null,
        boardCount: null,
        boardRace: "",
        boardGender: "",
        staffRace: "",
        staffGender: "",
        topZips: "",
        guidestarUrl: "",
        lastVerified: null,
        verifiedBy: "Not yet verified",
      },
    ],
    docs: [
      {
        id: "fixturegoodstanding",
        org: "namifc",
        orgPageIds: ["fixturenamifacts"],
        name: "Certificate of Good Standing — Ohio SOS (2020)",
        type: "Good Standing",
        fileLink: "",
        issueDate: "2020-01-01",
        coversStart: null,
        coversEnd: null,
        expires: null,
        superseded: false,
        notes: "Nearly submitted in 2026. Order a fresh certificate before the next submission.",
      },
      {
        id: "fixture990",
        org: "namifc",
        orgPageIds: ["fixturenamifacts"],
        name: "IRS Form 990 — FY2023",
        type: "990",
        fileLink: "",
        issueDate: null,
        coversStart: "2022-07-01",
        coversEnd: "2023-06-30",
        expires: null,
        superseded: false,
        notes: "Most recent 990 on file.",
      },
      {
        id: "fixture501c3",
        org: "namifc",
        orgPageIds: ["fixturenamifacts"],
        name: "IRS 501(c)(3) Determination Letter",
        type: "501c3",
        fileLink: "",
        issueDate: null,
        coversStart: null,
        coversEnd: null,
        expires: null,
        superseded: false,
        notes: "",
      },
      {
        id: "fixtureagreement",
        org: "namifc",
        orgPageIds: ["fixturenamifacts"],
        name: "Measurement Ally Service Agreement — restated Aug 7, 2026",
        type: "Consultant Agreement",
        fileLink: "",
        issueDate: "2026-08-07",
        coversStart: "2026-06-10",
        coversEnd: "2026-11-30",
        expires: "2026-11-30",
        superseded: false,
        notes: "Renew before November if the Health Equity award is funded.",
      },
    ],
    blocks: [
      {
        id: "fixtureshort",
        org: null,
        name: "Consultant Disclosure — Short (one-line fields)",
        category: "Consultant Disclosure",
        text: "Dr. Erica L. Tartt (Measurement Ally), Evaluation & Grant Strategy Consultant, under an executed monthly retainer. Compensation is not contingent on award outcome.",
        notes: "Reuse verbatim.",
        lastUpdated: "2026-08-07T00:00:00Z",
      },
    ],
    fieldLog: [
      // LOI — as filed April 30
      { id: "f1", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Amount Requested", value: "$250,000", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f2", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Program Name", value: "FaithLink with Mental Health First Aid (MHFA) Expansion", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f3", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Total Persons Served", value: "500", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f4", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Service ZIP Codes", value: "43203, 43219, 43211", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f5", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Board Member Count", value: "9", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f6", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "MHFA Component", value: "Included — MHFA training track", charLimit: null, submittedDate: "2026-04-30" },
      { id: "f7", grantIds: ["fixturefaithlink"], phase: "LOI", fieldName: "Blueprint Goal", value: "#9", charLimit: null, submittedDate: "2026-04-30" },
      // Full — the pre-correction working draft (the drift the checker must catch)
      { id: "f8", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Amount Requested", value: "$200,000", charLimit: null, submittedDate: "2026-08-07" },
      { id: "f9", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Program Name", value: "FaithLink Health Equity Initiative", charLimit: null, submittedDate: "2026-08-07" },
      { id: "f10", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Total Persons Served", value: "197", charLimit: null, submittedDate: "2026-08-07" },
      { id: "f11", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Service ZIP Codes", value: "43205, 43206, 43207", charLimit: null, submittedDate: "2026-08-07" },
      { id: "f12", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Board Member Count", value: "14", charLimit: null, submittedDate: "2026-08-07" },
      { id: "f13", grantIds: ["fixturefaithlink"], phase: "Full", fieldName: "Blueprint Goal", value: "#9", charLimit: 1000, submittedDate: "2026-08-07" },
      // Note: no MHFA Component row in Full — the dropped component.
    ],
  };
}
